backend:
  name: git-gateway
  repo: koodi-info/_asiakas_paulette-ravintola
  branch: main # NOTE this relates to your GitHub branch
  local_backend: true
publish_mode: editorial_workflow
local_backend: true # allows for you to locally mess with your CMS
media_folder: "public/images/uploads" # Media files will be stored in the repo under public/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
editor:
  preview: false # we're going to hide the preview editor
collections:
  - label: "Sivuston elementit"
    name: "components"
    create: false
    files:
      - label: "Tervetuloa sisältö"
        name: "welcome"
        file: "src/content/welcome.json"
        fields:
          - { label: Ostikko, name: title, widget: string }
          - { label: Sisältö, name: intro, widget: text }
          - { label: "Valokuva", name: "image", widget: "image" }
      - label: "Covid19 info"
        name: "covid"
        file: "src/content/covid.json"
        fields:
          - { label: Julkinen, name: public, widget: boolean, default: true }
          - { label: Ostikko, name: title, widget: string }
          - { label: Sisältö, name: body, widget: text }
      - label: "Yhteystiedot sekä aukioloajat"
        name: "contact"
        file: "src/content/contact.json"
        fields:
          - { label: Osoite, name: address, widget: string }
          - { label: Sähköposti, name: email, widget: string }
          - { label: Puhelinnumero, name: phone, widget: string }
          - {
              label: Ajankohtaista,
              name: news,
              widget: markdown,
              modes: [raw],
              buttons: [bold],
            }
          - label: Aukioloajat
            name: opening_hours
            widget: list
            fields:
              - { label: Aukioloaika, name: item, widget: string }
          - label: Poikkeusaukioloajat
            name: exception_opening_hours
            widget: list
            fields:
              - { label: Poikkeusaika, name: item, widget: string }
      - label: "Ilmoitustaulu"
        name: "extra-info"
        file: "src/content/extra-info.json"
        fields:
          - { label: Julkinen, name: public, widget: boolean, default: true }
          - { label: Otsikko, name: heading, widget: string }
          - {
              label: Sisältö,
              name: content,
              widget: markdown,
              modes: [raw],
              buttons: [bold],
            }
      - label: "Lounas ruokalista"
        name: "lunch"
        file: "src/content/lunch-list.json"
        fields:
          - {
              label: "Lounaslista viikolle",
              name: "week",
              widget: "select",
              options:
                [
                  "1",
                  "2",
                  "3",
                  "4",
                  "5",
                  "6",
                  "7",
                  "8",
                  "9",
                  "10",
                  "11",
                  "12",
                  "13",
                  "14",
                  "15",
                  "16",
                  "17",
                  "18",
                  "19",
                  "20",
                  "21",
                  "22",
                  "23",
                  "24",
                  "25",
                  "26",
                  "27",
                  "28",
                  "29",
                  "30",
                  "31",
                  "32",
                  "33",
                  "34",
                  "35",
                  "36",
                  "37",
                  "38",
                  "39",
                  "40",
                  "41",
                  "42",
                  "43",
                  "44",
                  "45",
                  "46",
                  "47",
                  "48",
                  "49",
                  "50",
                  "51",
                  "52",
                ],
            }
          - { label: "Valokuva 1", name: "imageone", widget: "image" }
          - { label: "Valokuva 2", name: "imagetwo", widget: "image" }
          - { label: "Valokuva 3", name: "imagethree", widget: "image" }
          - label: Lounas annokset
            name: foods
            widget: list
            fields:
              - { label: Annoksen nimi, name: title, widget: string }
              - {
                  label: Annoksen sisältö,
                  name: content,
                  widget: markdown,
                  modes: [raw],
                  buttons: [bold],
                }
              - { label: "Annoksen hinta", name: "price", widget: "string" }
              - label: "Annoksen tyyppi"
                name: "type"
                widget: "select"
                options: ["Lounas", "Alkuruoka", "Pääruoka", "Jälkiruoka"]
          - label: Lounas juomat
            name: drinks
            widget: list
            fields:
              - { label: Juoman nimi, name: title, widget: string }
              - { label: "Juoman hinta", name: "price", widget: "string" }
              - label: "Juoman tyyppi"
                name: "type"
                widget: "select"
                options:
                  [
                    { label: "Kahvi", value: "Kahvi" },
                    { label: "Virvoitusjuoma", value: "Kahvi" },
                    { label: "Alkoholittomat", value: "Alkoholittomat" },
                    { label: "Olut / Siideri", value: "Olut / Siideri" },
                    { label: "Viini", value: "Viini" },
                  ]

      - label: "Extra ruokalista"
        widget: "list"
        name: "extralist"
        file: "src/content/extra-list.json"
        fields:
          - { label: Ruokalistan otsikko, name: title, widget: string }
          - { label: Julkinen, name: public, widget: boolean, default: true }
          - { label: Yhteishinta, name: price, widget: string }
          - { label: Aputeksti, name: info, widget: markdown, modes: [raw]}
          - label: Annokset
            name: foods
            widget: list
            fields:
              - { label: Annoksen nimi, name: title, widget: string }
              - {
                  label: Annoksen sisältö,
                  name: content,
                  widget: markdown,
                  modes: [raw],
                  buttons: [bold],
                }
              - { label: "Annoksen hinta", name: "price", widget: "string" }
              - {
                  label: "Hinta julkinen",
                  name: price_public,
                  widget: boolean,
                  default: true,
                }
              - label: "Annoksen tyyppi"
                name: "type"
                widget: "select"
                options: ["Alkuruoka", "Pääruoka", "Jälkiruoka", "Plateau de"]
              - {
                  label: "Valinta vaihtoehto",
                  name: choice,
                  widget: boolean,
                  default: false,
                }
          - label: Extra juomat
            name: drinks
            widget: list
            fields:
              - { label: Juoman nimi, name: title, widget: string }
              - {
                  label: "Juoman kuvaus",
                  name: "description",
                  widget: "string",
                }
              - { label: "Juoman hinta", name: "price", widget: "string" }
              - label: "Juoman tyyppi"
                name: "type"
                widget: "select"
                options:
                  [
                    { label: "Muut juomat", value: "Other drinks" },
                    { label: "Valkoviini", value: "White Wine" },
                    { label: "Punaviini", value: "Red Wine" },
                    { label: "Kuohuviini", value: "Sparkling Wine" },
                    { label: "Rose", value: "Rose" },
                  ]

      - label: "A la carte ruokalista"
        name: "alacarte"
        file: "src/content/ala-carte-list.json"
        fields:
          - { label: "Valokuva 1", name: "imageone", widget: "image" }
          - { label: "Valokuva 2", name: "imagetwo", widget: "image" }
          - { label: "Valokuva 3", name: "imagethree", widget: "image" }
          - label: A ala carte annokset
            name: foods
            widget: list
            fields:
              - { label: Annoksen nimi, name: title, widget: string }
              - {
                  label: Annoksen sisältö,
                  name: content,
                  widget: markdown,
                  modes: [raw],
                  buttons: [bold],
                }
              - { label: "Annoksen hinta", name: "price", widget: "string" }
              - label: "Annoksen tyyppi"
                name: "type"
                widget: "select"
                options: ["Alkuruoka", "Pääruoka", "Jälkiruoka", "Plateau de"]
          - label: A la carte juomat
            name: drinks
            widget: list
            fields:
              - { label: Juoman nimi, name: title, widget: string }
              - {
                  label: "Juoman kuvaus",
                  name: "description",
                  widget: "string",
                }
              - { label: "Juoman hinta", name: "price", widget: "string" }
              - label: "Juoman tyyppi"
                name: "type"
                widget: "select"
                options:
                  [
                    { label: "Muut juomat", value: "Other drinks" },
                    { label: "Valkoviini", value: "White Wine" },
                    { label: "Punaviini", value: "Red Wine" },
                    { label: "Kuohuviini", value: "Sparkling Wine" },
                    { label: "Rose", value: "Rose" },
                  ]

      - label: "Esittely osiot"
        name: "about"
        file: "src/content/about-us.json"
        fields:
          - label: Osion sisältö
            widget: list
            name: about_content
            fields:
              - { label: Otsikko, name: title, widget: string }
              - {
                  label: "Sisätö",
                  name: "body",
                  widget: markdown,
                  modes: [rich_text],
                  buttons: [bold],
                }
              - { label: "Vasen valokuva", name: "leftImage", widget: "image" }
              - { label: "Oikea valokuva", name: "rightImage", widget: "image" }
